name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}

    - name: install dependencies
      run: npm install

    - name: build
      run: npm run build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: deploy-vercel
      url: 'https://liroustore.vercel.app/'
    steps:
    - name: deploy
      run: curl --location https://api.vercel.com/v1/integrations/deploy/prj_3xqNsOOgERDXYD5OTG3XbcaJblv2/ZqwP2Gp1hS
        
